name: Update Golf Calendar

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Belgian time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run golf calendar script
      env:
        I_GOLF_USERNAME: ${{ secrets.I_GOLF_USERNAME }}
        I_GOLF_PASSWORD: ${{ secrets.I_GOLF_PASSWORD }}
      run: |
        python github_action.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golf.ics
        git diff --quiet && git diff --staged --quiet || git commit -m "Update golf calendar - $(date +'%Y-%m-%d %H:%M:%S')"
        git push 