name: Update Golf Calendar

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Belgian time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        echo "=== STARTING CHROME/CHROMEDRIVER INSTALLATION ==="
        
        # Update packages
        echo "Updating packages..."
        sudo apt-get update
        sudo apt-get install -y wget unzip curl jq
        
        # Check what's already installed
        echo "=== CHECKING EXISTING INSTALLATIONS ==="
        echo "System Chrome:"
        google-chrome --version || echo "No system Chrome found"
        
        echo "System ChromeDriver:"
        chromedriver --version || echo "No system ChromeDriver found"
        
        echo "=== DETERMINING CHROME VERSION ==="
        CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+' | head -1)
        echo "Detected Chrome version: $CHROME_VERSION"
        
        # Always use a specific, known-working approach
        echo "=== USING KNOWN WORKING CHROMEDRIVER SETUP ==="
        
        # Remove any existing ChromeDriver
        sudo rm -f /usr/local/bin/chromedriver
        sudo rm -f /usr/bin/chromedriver
        
        # Download a specific ChromeDriver version that works with Chrome 138
        echo "Downloading ChromeDriver 120.0.6099.109 (known to work with newer Chrome)..."
        wget -q "https://chromedriver.storage.googleapis.com/120.0.6099.109/chromedriver_linux64.zip" -O /tmp/chromedriver.zip
        
        echo "Checking if download succeeded..."
        ls -la /tmp/chromedriver.zip
        
        echo "Extracting ChromeDriver..."
        unzip -q /tmp/chromedriver.zip -d /tmp/
        
        echo "Installing ChromeDriver..."
        sudo cp /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        echo "=== VERIFICATION ==="
        echo "ChromeDriver location:"
        which chromedriver
        
        echo "ChromeDriver version:"
        chromedriver --version
        
        echo "ChromeDriver permissions:"
        ls -la /usr/local/bin/chromedriver
        
        echo "=== TESTING CHROME BINARY ==="
        echo "System Chrome binary:"
        which google-chrome
        
        echo "System Chrome version:"
        google-chrome --version
        
        echo "=== ENVIRONMENT SETUP ==="
        echo "Setting up environment variables..."
        echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV
        
        echo "Environment variables set:"
        echo "CHROME_BIN: $(which google-chrome)"
        echo "CHROMEDRIVER_PATH: /usr/local/bin/chromedriver"
        
        echo "=== INSTALLATION COMPLETE ==="
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run golf calendar script
      env:
        I_GOLF_USERNAME: ${{ secrets.I_GOLF_USERNAME }}
        I_GOLF_PASSWORD: ${{ secrets.I_GOLF_PASSWORD }}
      run: |
        python github_action.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golf.ics
        git diff --quiet && git diff --staged --quiet || git commit -m "Update golf calendar - $(date +'%Y-%m-%d %H:%M:%S')"
        git push 