name: Update Golf Calendar

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Belgian time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable wget unzip
        
        # Download and install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        echo "Chrome version: $CHROME_VERSION"
        
        # Download ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" -O /tmp/chromedriver_version
        CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver_version)
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # Install ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O /tmp/chromedriver.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run golf calendar script
      env:
        I_GOLF_USERNAME: ${{ secrets.I_GOLF_USERNAME }}
        I_GOLF_PASSWORD: ${{ secrets.I_GOLF_PASSWORD }}
      run: |
        python github_action.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golf.ics
        git diff --quiet && git diff --staged --quiet || git commit -m "Update golf calendar - $(date +'%Y-%m-%d %H:%M:%S')"
        git push 