name: Update Golf Calendar

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Belgian time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Setup ChromeDriver
      run: |
        echo "=== CHROMEDRIVER SETUP ==="
        
        # Use the ChromeDriver that comes with the browser-actions/setup-chrome action
        echo "ChromeDriver should be automatically available"
        
        # Check what's available
        echo "Available ChromeDriver:"
        which chromedriver || echo "ChromeDriver not in PATH"
        
        echo "ChromeDriver version:"
        chromedriver --version || echo "ChromeDriver not working"
        
        echo "Chrome version:"
        google-chrome --version || echo "Chrome not working"
        
        # Set environment variables
        echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV
        
        echo "Environment variables set:"
        echo "CHROME_BIN: $(which google-chrome)"
        echo "CHROMEDRIVER_PATH: $(which chromedriver)"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run golf calendar script
      env:
        I_GOLF_USERNAME: ${{ secrets.I_GOLF_USERNAME }}
        I_GOLF_PASSWORD: ${{ secrets.I_GOLF_PASSWORD }}
      run: |
        python github_action.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golf.ics
        git diff --quiet && git diff --staged --quiet || git commit -m "Update golf calendar - $(date +'%Y-%m-%d %H:%M:%S')"
        git push 