name: Update Golf Calendar

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Belgian time)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+' | head -1)
        echo "Chrome version: $CHROME_VERSION"
        
        # For Chrome 115+, use Chrome for Testing
        if [ "$CHROME_VERSION" -ge 115 ]; then
          echo "Using Chrome for Testing (Chrome $CHROME_VERSION)"
          
          # Download Chrome for Testing
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/stable/linux64/chrome-linux64.zip" -O /tmp/chrome-linux64.zip
          unzip /tmp/chrome-linux64.zip -d /tmp/
          
          # Download ChromeDriver for Testing
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/stable/linux64/chromedriver-linux64.zip" -O /tmp/chromedriver-linux64.zip
          unzip /tmp/chromedriver-linux64.zip -d /tmp/
          
          # Install ChromeDriver
          sudo cp /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Set Chrome binary path
          echo "export CHROME_BIN=/tmp/chrome-linux64/chrome" >> $GITHUB_ENV
        else
          echo "Using traditional ChromeDriver"
          
          # Download and install ChromeDriver
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O /tmp/chromedriver.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
        fi
        
        # Verify installation
        chromedriver --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run golf calendar script
      env:
        I_GOLF_USERNAME: ${{ secrets.I_GOLF_USERNAME }}
        I_GOLF_PASSWORD: ${{ secrets.I_GOLF_PASSWORD }}
      run: |
        python github_action.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golf.ics
        git diff --quiet && git diff --staged --quiet || git commit -m "Update golf calendar - $(date +'%Y-%m-%d %H:%M:%S')"
        git push 